config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dishes#index"
  resources :dishes 
    resources :comments,only: :create
   
   resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :dish


  validates :text, presence: true
end

app/models/dish.rb
class Dish < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many         :comments, dependent: :destroy
  
    validates :title,     presence: true
    validates :category,  presence: true
    validates :material,  presence: true
    validates :one,       presence: true
    validates :two,       presence: true
    validates :three,     presence: true
    validates :image,     presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :nickname, presence: true
    validates :profile,  presence: true

   has_many :dishes  
   has_many :comment
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.cretate(comment_params)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, dish_id: params[:dish_id])
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :create]

  def index
    @dishes = Dish.all
  end

  def new
    @dish = Dish.new
  end

  def create
     Dish.new(dish_params)
   if 
    Dish.create(dish_params)
    redirect_to root_path
   else
     render :new
    end
  end

  def show
    @dish = Dish.find(params[:id])
    @comment = Comment.new
    @comments = @dish.comments.includes(:user)
  end

  def edit
    @dish = Dish.find(params[:id])
  end


  def update
    @dish = Dish.find(params[:id])
    @dish.update(dish_params)
  end

  def destroy
    dish = Dish.find(params[:id])
    dish.destroy
    redirect_to root_path
  end

  private

  def dish_params
    params.require(:dish).permit(:title, :category, :material, :one, :two, :three, :image, :user).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reshipi_helper.rb
module ReshipiHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_dish.html.erb
<div class="card">
  <%= link_to image_tag(dish.image, class: :card__img ), dish_path(dish) %>
  <div class="card__body"> 
    <%= link_to dish.title, root_path, class: :card__title %>
    <p class="card__summary">
      <%= dish.category %>
    </p>
    <%= link_to "投稿者 #{dish.user.nickname}", root_path, class: :card__user %>
  </div>
</div>

app/views/dishes/_form.html.erb
<%= form_with model: @dish, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "料理タイトル" %><br />
    <%= f.text_field :title, id:"dish_title" %>
  </div>

  <div class="field">
    <%= f.label :category, "カテゴリー" %><br />
    <%= f.text_area :category, class: :form__text, id:"dish_category" %>
  </div>

  <div class="field">
    <%= f.label :material, "材料" %><br />
    <%= f.text_area :material, class: :form__text, id:"dish_material" %>
  </div>

  <div class="field">
    <%= f.label :one, "作り方.1" %><br />
    <%= f.text_area :one, class: :form__text, id:"dish_one" %>
  </div>

   <div class="field">
    <%= f.label :two, "作り方.2" %><br />
    <%= f.text_area :two, class: :form__text, id:"dish_two" %>
  </div>

  <div class="field">
    <%= f.label :three, "作り方.3" %><br />
    <%= f.text_area :three, class: :form__text, id:"dish_three" %>
  </div>


  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"dish_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
      <%= render partial: "form", locals: { dish: @dish } %>
    </div>
  </div>
</div>

app/views/dishes/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "ようこそ#{current_user.nickname}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'dish', collection: @dishes %>
    </div>
  </div>
</main>

app/views/dishes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規レシピ投稿</h2>
      <%= render partial: "form", locals:{ dish: @dish }%>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="dish__wrapper">
      <p class="dish__hedding">
        <%= @dish.title %>
      </p>
     
      <div class="dish__image">
      <%= image_tag @dish.image %>
      </div>
      <div class="dish__body">
        <div class="dish__detail">
          <p class="detail__title">カテゴリー</p>
          <p class="detail__message">
            <%= @dish.category %>
          </p>
        </div>
        <div class="desh__detail">
          <p class="detail__title">材料</p>
          <p class="detail__message">
            <%= @dish.material %>
          </p>
        </div>
        <div class="desh__detail">
          <p class="detail__title">作り方</p>
          <p class="detail__message">
            <a class="nonber">1.<%= @dish.one %></a>
            <a class="nonber">2.<%= @dish.two %></a>
            <a class="nonber">3.<%= @dish.three %></a>
          </p>
        </div>
      </div>

       <%= link_to "投稿者 #{@dish.user.nickname}", user_path(@dish.user), class: :dish__user %>
       <% if current_user == @dish.user %>
        <div class="dish__manage">
          <%= link_to "編集する", edit_dish_path(@dish), class: :dish__btn %>
          <%= link_to "削除する", dish_path(@dish), method: :delete, class: :dish__btn %>
        </div>
      <% end %>

      <div class="dish__comments">
      <% if user_signed_in? %>
        <%= form_with model: [@dish],local: true do |f|%>
            <div class="field">
               <%= f.label :text, "コメント" %><br />
               <%= f.text_field :text, id:"comment_content" %>
        <% end %>
            </div>
            <div class="actions">
               <%#= f.submit "送信する", class: :form__btn  %>
            </div>
           <% end %>
       
        <ul class="comments_lists">
           <%# @dish.each do |dish| %>
            <li class="comments_list">
            <%#= comment.text %>
            <%#= link_to "（#{comments.user.nickname}）", user_path(comment.user), class: :comment_user %>
            </li>
        <%# end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>三行レシピ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.jpg", class: :logo), root_path %>
       
          </div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout%>
              <%= link_to "レシピ投稿",new_dish_path, class: :nav__btn %>
            </div>

          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © mmitsuko</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さん"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1"></th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿一覧"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'dishes/dish', collection: @user.dishes %>
      </div>
    </div>
  </div>
</div>